# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Connor Yager
email: csy7ay@virginia.edu
description: > # this means to ignore newlines until "baseurl:"
  My personal website, where I keep updates on projects that I'm working on, 
  notable events in my life, and other such information.  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: connor_yager
github_username:  csyager

# Build settings
markdown: kramdown

exclude: feed.xml
exclude: css/main.css
